version: 3
workdir: .
allow:
  depOnAnyVendor: true
  deepScan: false

components:
  pkg_clientai:
    in: pkg/clientai/**
  pkg_lib:
    in:
      - pkg/logger/**
      - pkg/fshelper/**
      - pkg/metric/**
      - pkg/version/**
  adapter:
    in: internal/adapter/**
  application:
    in: internal/application/**
  di:
    in: internal/di/**
  core:
    in: internal/core/usecase/**
  domain:
    in: internal/core/domain/**
  apperror:
    in: internal/core/apperror/**
  presenter:
    in: internal/presenter/**
  cmd:
    in: cmd/**
  tests:
    in: tests/**

deps:
  pkg_clientai:
    mayDependOn:
      - pkg_clientai
  pkg_lib:
    mayDependOn:
      - pkg_lib
  adapter:
    mayDependOn:
      - adapter
      - apperror
      - domain
      - pkg_clientai
      - pkg_lib
  core:
    mayDependOn:
      - apperror
      - core
      - domain
      - pkg_lib
  domain:
    mayDependOn:
      - domain
  apperror:
    mayDependOn:
      - apperror
  presenter:
    mayDependOn:
      - core
      - presenter
      - domain
      - pkg_lib
  di:
    mayDependOn:
      - adapter
      - application
      - core
      - di
      - presenter
      - domain
      - pkg_clientai
      - pkg_lib
  application:
    mayDependOn:
      - adapter
      - application
      - apperror
      - core
      - di
      - presenter
      - domain
      - pkg_lib
  cmd:
    mayDependOn:
      - application
      - pkg_lib
  tests:
    mayDependOn:
      - tests
