all: false
force-file-write: true
formatter: goimports
log-level: info
structname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
filename: '{{.InterfaceFile | base | trimSuffix ".go"}}_mock.go'
dir: "{{.InterfaceDir}}"
packages:
  github.com/POSIdev-community/aictl/internal/core/usecase/set/project/settings:
    config:
      all: true
  github.com/POSIdev-community/aictl/internal/core/usecase/get/scan/report/defaultreport:
    config:
      all: true
