// Code generated by "enumer -type ReportType -text -transform=lower"; DO NOT EDIT.

package report

import (
	"fmt"
	"strings"
)

const _ReportTypeName = "autocheckcustomgitlabjsonjsonv2markdownnistoud4owaspowaspmpcidssplainreportsanssarifxml"

var _ReportTypeIndex = [...]uint8{0, 9, 15, 21, 25, 31, 39, 43, 47, 52, 58, 64, 75, 79, 84, 87}

const _ReportTypeLowerName = "autocheckcustomgitlabjsonjsonv2markdownnistoud4owaspowaspmpcidssplainreportsanssarifxml"

func (i ReportType) String() string {
	if i >= ReportType(len(_ReportTypeIndex)-1) {
		return fmt.Sprintf("ReportType(%d)", i)
	}
	return _ReportTypeName[_ReportTypeIndex[i]:_ReportTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ReportTypeNoOp() {
	var x [1]struct{}
	_ = x[AutoCheck-(0)]
	_ = x[Custom-(1)]
	_ = x[Gitlab-(2)]
	_ = x[Json-(3)]
	_ = x[JsonV2-(4)]
	_ = x[Markdown-(5)]
	_ = x[Nist-(6)]
	_ = x[Oud4-(7)]
	_ = x[Owasp-(8)]
	_ = x[Owaspm-(9)]
	_ = x[Pcidss-(10)]
	_ = x[PlainReport-(11)]
	_ = x[Sans-(12)]
	_ = x[Sarif-(13)]
	_ = x[Xml-(14)]
}

var _ReportTypeValues = []ReportType{AutoCheck, Custom, Gitlab, Json, JsonV2, Markdown, Nist, Oud4, Owasp, Owaspm, Pcidss, PlainReport, Sans, Sarif, Xml}

var _ReportTypeNameToValueMap = map[string]ReportType{
	_ReportTypeName[0:9]:        AutoCheck,
	_ReportTypeLowerName[0:9]:   AutoCheck,
	_ReportTypeName[9:15]:       Custom,
	_ReportTypeLowerName[9:15]:  Custom,
	_ReportTypeName[15:21]:      Gitlab,
	_ReportTypeLowerName[15:21]: Gitlab,
	_ReportTypeName[21:25]:      Json,
	_ReportTypeLowerName[21:25]: Json,
	_ReportTypeName[25:31]:      JsonV2,
	_ReportTypeLowerName[25:31]: JsonV2,
	_ReportTypeName[31:39]:      Markdown,
	_ReportTypeLowerName[31:39]: Markdown,
	_ReportTypeName[39:43]:      Nist,
	_ReportTypeLowerName[39:43]: Nist,
	_ReportTypeName[43:47]:      Oud4,
	_ReportTypeLowerName[43:47]: Oud4,
	_ReportTypeName[47:52]:      Owasp,
	_ReportTypeLowerName[47:52]: Owasp,
	_ReportTypeName[52:58]:      Owaspm,
	_ReportTypeLowerName[52:58]: Owaspm,
	_ReportTypeName[58:64]:      Pcidss,
	_ReportTypeLowerName[58:64]: Pcidss,
	_ReportTypeName[64:75]:      PlainReport,
	_ReportTypeLowerName[64:75]: PlainReport,
	_ReportTypeName[75:79]:      Sans,
	_ReportTypeLowerName[75:79]: Sans,
	_ReportTypeName[79:84]:      Sarif,
	_ReportTypeLowerName[79:84]: Sarif,
	_ReportTypeName[84:87]:      Xml,
	_ReportTypeLowerName[84:87]: Xml,
}

var _ReportTypeNames = []string{
	_ReportTypeName[0:9],
	_ReportTypeName[9:15],
	_ReportTypeName[15:21],
	_ReportTypeName[21:25],
	_ReportTypeName[25:31],
	_ReportTypeName[31:39],
	_ReportTypeName[39:43],
	_ReportTypeName[43:47],
	_ReportTypeName[47:52],
	_ReportTypeName[52:58],
	_ReportTypeName[58:64],
	_ReportTypeName[64:75],
	_ReportTypeName[75:79],
	_ReportTypeName[79:84],
	_ReportTypeName[84:87],
}

// ReportTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ReportTypeString(s string) (ReportType, error) {
	if val, ok := _ReportTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ReportTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ReportType values", s)
}

// ReportTypeValues returns all values of the enum
func ReportTypeValues() []ReportType {
	return _ReportTypeValues
}

// ReportTypeStrings returns a slice of all String values of the enum
func ReportTypeStrings() []string {
	strs := make([]string, len(_ReportTypeNames))
	copy(strs, _ReportTypeNames)
	return strs
}

// IsAReportType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ReportType) IsAReportType() bool {
	for _, v := range _ReportTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for ReportType
func (i ReportType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ReportType
func (i *ReportType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ReportTypeString(string(text))
	return err
}
