// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package default_report

import (
	"context"
	"io"

	"github.com/POSIdev-community/aictl/internal/core/domain/report"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// GetDefaultTemplateId provides a mock function for the type MockAI
func (_mock *MockAI) GetDefaultTemplateId(ctx context.Context, reportType report.ReportType) (uuid.UUID, error) {
	ret := _mock.Called(ctx, reportType)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultTemplateId")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, report.ReportType) (uuid.UUID, error)); ok {
		return returnFunc(ctx, reportType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, report.ReportType) uuid.UUID); ok {
		r0 = returnFunc(ctx, reportType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, report.ReportType) error); ok {
		r1 = returnFunc(ctx, reportType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetDefaultTemplateId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultTemplateId'
type MockAI_GetDefaultTemplateId_Call struct {
	*mock.Call
}

// GetDefaultTemplateId is a helper method to define mock.On call
//   - ctx context.Context
//   - reportType report.ReportType
func (_e *MockAI_Expecter) GetDefaultTemplateId(ctx interface{}, reportType interface{}) *MockAI_GetDefaultTemplateId_Call {
	return &MockAI_GetDefaultTemplateId_Call{Call: _e.mock.On("GetDefaultTemplateId", ctx, reportType)}
}

func (_c *MockAI_GetDefaultTemplateId_Call) Run(run func(ctx context.Context, reportType report.ReportType)) *MockAI_GetDefaultTemplateId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 report.ReportType
		if args[1] != nil {
			arg1 = args[1].(report.ReportType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAI_GetDefaultTemplateId_Call) Return(uUID uuid.UUID, err error) *MockAI_GetDefaultTemplateId_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockAI_GetDefaultTemplateId_Call) RunAndReturn(run func(ctx context.Context, reportType report.ReportType) (uuid.UUID, error)) *MockAI_GetDefaultTemplateId_Call {
	_c.Call.Return(run)
	return _c
}

// GetReport provides a mock function for the type MockAI
func (_mock *MockAI) GetReport(ctx context.Context, projectId uuid.UUID, scanResultId uuid.UUID, templateId uuid.UUID, includeComments bool, includeDFD bool, includeGlossary bool, l10n string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary, l10n)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, bool, bool, bool, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary, l10n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, bool, bool, bool, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary, l10n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, bool, bool, bool, string) error); ok {
		r1 = returnFunc(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary, l10n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type MockAI_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId uuid.UUID
//   - scanResultId uuid.UUID
//   - templateId uuid.UUID
//   - includeComments bool
//   - includeDFD bool
//   - includeGlossary bool
//   - l10n string
func (_e *MockAI_Expecter) GetReport(ctx interface{}, projectId interface{}, scanResultId interface{}, templateId interface{}, includeComments interface{}, includeDFD interface{}, includeGlossary interface{}, l10n interface{}) *MockAI_GetReport_Call {
	return &MockAI_GetReport_Call{Call: _e.mock.On("GetReport", ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary, l10n)}
}

func (_c *MockAI_GetReport_Call) Run(run func(ctx context.Context, projectId uuid.UUID, scanResultId uuid.UUID, templateId uuid.UUID, includeComments bool, includeDFD bool, includeGlossary bool, l10n string)) *MockAI_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockAI_GetReport_Call) Return(readCloser io.ReadCloser, err error) *MockAI_GetReport_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockAI_GetReport_Call) RunAndReturn(run func(ctx context.Context, projectId uuid.UUID, scanResultId uuid.UUID, templateId uuid.UUID, includeComments bool, includeDFD bool, includeGlossary bool, l10n string) (io.ReadCloser, error)) *MockAI_GetReport_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// ShowReader provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowReader(r io.Reader) error {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ShowReader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCLI_ShowReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowReader'
type MockCLI_ShowReader_Call struct {
	*mock.Call
}

// ShowReader is a helper method to define mock.On call
//   - r io.Reader
func (_e *MockCLI_Expecter) ShowReader(r interface{}) *MockCLI_ShowReader_Call {
	return &MockCLI_ShowReader_Call{Call: _e.mock.On("ShowReader", r)}
}

func (_c *MockCLI_ShowReader_Call) Run(run func(r io.Reader)) *MockCLI_ShowReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCLI_ShowReader_Call) Return(err error) *MockCLI_ShowReader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCLI_ShowReader_Call) RunAndReturn(run func(r io.Reader) error) *MockCLI_ShowReader_Call {
	_c.Call.Return(run)
	return _c
}

// ShowTextf provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowTextf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockCLI_ShowTextf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowTextf'
type MockCLI_ShowTextf_Call struct {
	*mock.Call
}

// ShowTextf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockCLI_Expecter) ShowTextf(ctx interface{}, format interface{}, args ...interface{}) *MockCLI_ShowTextf_Call {
	return &MockCLI_ShowTextf_Call{Call: _e.mock.On("ShowTextf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockCLI_ShowTextf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockCLI_ShowTextf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCLI_ShowTextf_Call) Return() *MockCLI_ShowTextf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowTextf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockCLI_ShowTextf_Call {
	_c.Run(run)
	return _c
}
