// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/settings"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAI creates a new instance of AI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AI {
	mock := &AI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AI is an autogenerated mock type for the AI type
type AI struct {
	mock.Mock
}

type AI_Expecter struct {
	mock *mock.Mock
}

func (_m *AI) EXPECT() *AI_Expecter {
	return &AI_Expecter{mock: &_m.Mock}
}

// GetDefaultSettings provides a mock function for the type AI
func (_mock *AI) GetDefaultSettings(ctx context.Context) (settings.ScanSettings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultSettings")
	}

	var r0 settings.ScanSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (settings.ScanSettings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) settings.ScanSettings); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(settings.ScanSettings)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AI_GetDefaultSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultSettings'
type AI_GetDefaultSettings_Call struct {
	*mock.Call
}

// GetDefaultSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AI_Expecter) GetDefaultSettings(ctx interface{}) *AI_GetDefaultSettings_Call {
	return &AI_GetDefaultSettings_Call{Call: _e.mock.On("GetDefaultSettings", ctx)}
}

func (_c *AI_GetDefaultSettings_Call) Run(run func(ctx context.Context)) *AI_GetDefaultSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AI_GetDefaultSettings_Call) Return(scanSettings settings.ScanSettings, err error) *AI_GetDefaultSettings_Call {
	_c.Call.Return(scanSettings, err)
	return _c
}

func (_c *AI_GetDefaultSettings_Call) RunAndReturn(run func(ctx context.Context) (settings.ScanSettings, error)) *AI_GetDefaultSettings_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type AI
func (_mock *AI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type AI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AI_Expecter) InitializeWithRetry(ctx interface{}) *AI_InitializeWithRetry_Call {
	return &AI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *AI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *AI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AI_InitializeWithRetry_Call) Return(err error) *AI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *AI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// SetProjectSettings provides a mock function for the type AI
func (_mock *AI) SetProjectSettings(ctx context.Context, projectId uuid.UUID, settings1 *settings.ScanSettings) error {
	ret := _mock.Called(ctx, projectId, settings1)

	if len(ret) == 0 {
		panic("no return value specified for SetProjectSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *settings.ScanSettings) error); ok {
		r0 = returnFunc(ctx, projectId, settings1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AI_SetProjectSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProjectSettings'
type AI_SetProjectSettings_Call struct {
	*mock.Call
}

// SetProjectSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId uuid.UUID
//   - settings1 *settings.ScanSettings
func (_e *AI_Expecter) SetProjectSettings(ctx interface{}, projectId interface{}, settings1 interface{}) *AI_SetProjectSettings_Call {
	return &AI_SetProjectSettings_Call{Call: _e.mock.On("SetProjectSettings", ctx, projectId, settings1)}
}

func (_c *AI_SetProjectSettings_Call) Run(run func(ctx context.Context, projectId uuid.UUID, settings1 *settings.ScanSettings)) *AI_SetProjectSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *settings.ScanSettings
		if args[2] != nil {
			arg2 = args[2].(*settings.ScanSettings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AI_SetProjectSettings_Call) Return(err error) *AI_SetProjectSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AI_SetProjectSettings_Call) RunAndReturn(run func(ctx context.Context, projectId uuid.UUID, settings1 *settings.ScanSettings) error) *AI_SetProjectSettings_Call {
	_c.Call.Return(run)
	return _c
}
