// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCLI creates a new instance of CLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CLI {
	mock := &CLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CLI is an autogenerated mock type for the CLI type
type CLI struct {
	mock.Mock
}

type CLI_Expecter struct {
	mock *mock.Mock
}

func (_m *CLI) EXPECT() *CLI_Expecter {
	return &CLI_Expecter{mock: &_m.Mock}
}
