// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package settings

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/settings"
	"github.com/POSIdev-community/aictl/internal/core/domain/version"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// GetDefaultSettings provides a mock function for the type MockAI
func (_mock *MockAI) GetDefaultSettings(ctx context.Context) (settings.ScanSettings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultSettings")
	}

	var r0 settings.ScanSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (settings.ScanSettings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) settings.ScanSettings); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(settings.ScanSettings)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetDefaultSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultSettings'
type MockAI_GetDefaultSettings_Call struct {
	*mock.Call
}

// GetDefaultSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) GetDefaultSettings(ctx interface{}) *MockAI_GetDefaultSettings_Call {
	return &MockAI_GetDefaultSettings_Call{Call: _e.mock.On("GetDefaultSettings", ctx)}
}

func (_c *MockAI_GetDefaultSettings_Call) Run(run func(ctx context.Context)) *MockAI_GetDefaultSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_GetDefaultSettings_Call) Return(scanSettings settings.ScanSettings, err error) *MockAI_GetDefaultSettings_Call {
	_c.Call.Return(scanSettings, err)
	return _c
}

func (_c *MockAI_GetDefaultSettings_Call) RunAndReturn(run func(ctx context.Context) (settings.ScanSettings, error)) *MockAI_GetDefaultSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockAI
func (_mock *MockAI) GetVersion(ctx context.Context) (version.Version, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 version.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (version.Version, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) version.Version); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(version.Version)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockAI_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) GetVersion(ctx interface{}) *MockAI_GetVersion_Call {
	return &MockAI_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx)}
}

func (_c *MockAI_GetVersion_Call) Run(run func(ctx context.Context)) *MockAI_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_GetVersion_Call) Return(version1 version.Version, err error) *MockAI_GetVersion_Call {
	_c.Call.Return(version1, err)
	return _c
}

func (_c *MockAI_GetVersion_Call) RunAndReturn(run func(ctx context.Context) (version.Version, error)) *MockAI_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectSettings provides a mock function for the type MockAI
func (_mock *MockAI) GetProjectSettings(ctx context.Context, projectId uuid.UUID) (settings.ScanSettings, error) {
	ret := _mock.Called(ctx, projectId)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectSettings")
	}

	var r0 settings.ScanSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (settings.ScanSettings, error)); ok {
		return returnFunc(ctx, projectId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) settings.ScanSettings); ok {
		r0 = returnFunc(ctx, projectId)
	} else {
		r0 = ret.Get(0).(settings.ScanSettings)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAI_GetProjectSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectSettings'
type MockAI_GetProjectSettings_Call struct {
	*mock.Call
}

// GetProjectSettings is a helper method to define mock.On call
func (_e *MockAI_Expecter) GetProjectSettings(ctx interface{}, projectId interface{}) *MockAI_GetProjectSettings_Call {
	return &MockAI_GetProjectSettings_Call{Call: _e.mock.On("GetProjectSettings", ctx, projectId)}
}

func (_c *MockAI_GetProjectSettings_Call) Run(run func(ctx context.Context, projectId uuid.UUID)) *MockAI_GetProjectSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(arg0, arg1)
	})

	return _c
}

func (_c *MockAI_GetProjectSettings_Call) Return(scanSettings settings.ScanSettings, err error) *MockAI_GetProjectSettings_Call {
	_c.Call.Return(scanSettings, err)

	return _c
}

func (_c *MockAI_GetProjectSettings_Call) RunAndReturn(run func(ctx context.Context, projectId uuid.UUID) (settings.ScanSettings, error)) *MockAI_GetProjectSettings_Call {
	_c.Call.Return(run)

	return _c
}

// SetProjectSettings provides a mock function for the type MockAI
func (_mock *MockAI) SetProjectSettings(ctx context.Context, projectId uuid.UUID, settings1 *settings.ScanSettings) error {
	ret := _mock.Called(ctx, projectId, settings1)

	if len(ret) == 0 {
		panic("no return value specified for SetProjectSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *settings.ScanSettings) error); ok {
		r0 = returnFunc(ctx, projectId, settings1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_SetProjectSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProjectSettings'
type MockAI_SetProjectSettings_Call struct {
	*mock.Call
}

// SetProjectSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId uuid.UUID
//   - settings1 *settings.ScanSettings
func (_e *MockAI_Expecter) SetProjectSettings(ctx interface{}, projectId interface{}, settings1 interface{}) *MockAI_SetProjectSettings_Call {
	return &MockAI_SetProjectSettings_Call{Call: _e.mock.On("SetProjectSettings", ctx, projectId, settings1)}
}

func (_c *MockAI_SetProjectSettings_Call) Run(run func(ctx context.Context, projectId uuid.UUID, settings1 *settings.ScanSettings)) *MockAI_SetProjectSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *settings.ScanSettings
		if args[2] != nil {
			arg2 = args[2].(*settings.ScanSettings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAI_SetProjectSettings_Call) Return(err error) *MockAI_SetProjectSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_SetProjectSettings_Call) RunAndReturn(run func(ctx context.Context, projectId uuid.UUID, settings1 *settings.ScanSettings) error) *MockAI_SetProjectSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}
